blog/urls.py
"""
blog app URL Configuration
"""
from django.urls import path
from . import views


urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('post/<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='post_like'),
    path('add_post/', views.AddPostView.as_view(), name='add_post'),
    path(
        'post/edit/<slug:slug>',
        views.UpdatePostView.as_view(),
        name='update_post'
    ),
    path(
        'post/remove/<slug:slug>',
        views.DeletePostView.as_view(),
        name='delete_post'
    ),
    path(
        'category/<str:cats>/',
        views.CategoryView.as_view(),
        name='category'
    ),
    path('about/', views.About.as_view(), name='about'),
    path(
        'accessibility_statement/',
        views.AccessibilityStatement.as_view(),
        name='accessibility_statement',
    ),
    path(
        'copyright_statement/',
        views.CopyrightStatement.as_view(),
        name='copyright_statement',
    ),
    path(
        'user_agreement/',
        views.UserAgreement.as_view(),
        name='user_agreement'
    ),
]

contact/urls.py
"""
contact app URL Configuration
"""
from django.urls import path
from . import views


urlpatterns = [
    path('', views.contact, name='contact'),
]

fresh_casts/urls.py
"""
fresh_casts URL Configuration
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'), name='blog_urls'),
    path('contact/', include('contact.urls'), name='contacts'),
    path('member/', include('member.urls'), name='member'),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
]

blog/models.py
""" Models the Category, Blog Posts and Comments """
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model
from django_extensions.db.fields import AutoSlugField
from cloudinary.models import CloudinaryField


# Global Variables
STATUS = ((0, 'Draft'), (1, 'Published'))
User = get_user_model()


class Category(models.Model):
    """
    Models the fields for Post Categories.
    This enables separate views of posts
    by category value.
    Choice of 5 categories assigned when adding a post.
    """
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """ Keeps users on the same page """
        return reverse('home')

    class Meta:
        verbose_name_plural = 'categories'


class Post(models.Model):
    """
    Models the fields for a blog Post.
    """
    title = models.CharField(max_length=255, unique=True, primary_key=True)
    slug = AutoSlugField(populate_from='title', unique=True,)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts'
    )
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=False
    )
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField(max_length=5000)
    excerpt = models.TextField(max_length=180, blank=True)
    podcast_url = models.URLField(max_length=255)
    featured_image = CloudinaryField(
        'sample.webp', default='placeholder',
        transformation={'height': '300', 'width': '300', 'crop': 'fit'})
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='blogpost_like', blank=True
    )

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        """
        Counts number of blog post likes
        Returns number of blog post likes
        """
        return self.likes.count()

    def get_absolute_url(self):
        """ Keeps users on the same page """
        return reverse("home")


class Comment(models.Model):
    """
    Models the fields for adding Post Comments.
    """
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments'
    )
    username = models.ForeignKey(User, on_delete=models.CASCADE,
                                 related_name='user_comments')
    message = models.TextField(help_text='Add your comment here')
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return f'Comment {self.message} by {self.username}'

contact/models.py
"""
Standard Django database models
Standard Django timezone for date stamping
"""
from django.db import models
from django.utils import timezone


class Contact(models.Model):
    """
    Models the fields for the Contact Form.
    Additional admin feature to change status
    of forms as processed.
    """
    FORM_STATUS = (
        ('Open', 'Open'),
        ('Responded', 'Responded'),
        ('Complete', 'Complete')
    )

    name = models.CharField(max_length=155)
    email = models.EmailField(max_length=155)
    subject = models.CharField(max_length=200)
    message = models.CharField(max_length=2000)
    date_submitted = models.DateTimeField(default=timezone.now)
    contact_status = models.CharField(
        max_length=15, choices=FORM_STATUS, default=1)

    class Meta:
        """ Set verbose name """
        verbose_name = 'Contact Form'
        verbose_name_plural = 'Contact Forms'

contact/forms.py
"""
Form configuration for contact app
"""
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    """
    Fields used for Contact Us
    form from Contact Model
    """
    name = forms.CharField(
        max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    email = forms.EmailField(
        max_length=150,
        widget=forms.EmailInput(attrs={'class': 'form-control'})
    )
    subject = forms.CharField(
        max_length=150, widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    message = forms.CharField(
        widget=forms.Textarea(
                attrs={'class': 'form-control',
                       'placeholder': 'Add your message here'}))

    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'message')

contact/views.py
"""
Django imports to support Views
"""
from django.core.mail import send_mail
from django.contrib import messages
from django.conf import settings
from django.shortcuts import render, redirect, reverse
from .forms import ContactForm


def contact(request, *args, **kwargs):
    """
    Displays Contact Us page form.
    Uses Post method to send contact form.
    Validation checks performed on input before saving.
    Email sent externally to Fresh Casts Gmail.
    Retains user on same page after commenting.
    """
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name'],
            email = form.cleaned_data['email'],
            subject = form.cleaned_data['subject'],
            message = form.cleaned_data['message'],

            # send mail combining field forms
            send_mail({subject}, f'{name}, {email}, {message}',
                      settings.EMAIL_HOST_USER, [settings.EMAIL_HOST_USER],
                      fail_silently=False)
            messages.success(
                request, 'Thank you for contacting Fresh Casts \
                - we will reply within 24 hours!')

            # redirect to home page
            return redirect(reverse('home'))
        else:
            messages.error(
                request, 'Something went wrong with your submission.\
                Please try again.'
            )
    # blank form created if any other method is used
    else:
        form = ContactForm()

    return render(request, 'contact.html', {'form': form})

templates/add_post.html
{% extends 'base.html' %}
{% load i18n %}
{% load cloudinary %}
{% cloudinary post.featured_image format="jpg" width=300 height=300 %}
{% block title %}{% trans 'Add Blog Post' %}{% endblock %}
{% load crispy_forms_tags %}
{% block content %}
<!-- User will be logged in to access this page -->
{% if user.is_authenticated %}
<!-- Main container for page content : Adding a Blog Post -->
<div class="container">
  <div class="row">
    <div class="col-md-8 mt-3 offset-md-2">
      <div class="card-body">
        <!-- Page title -->
        <h2 class="card-title">{% trans 'Add Blog Post' %}
        </h2>
        <p class="card-text">Complete all fields in the form below and submit to the team who will review and publish
          within 24 hours. Please note that currently due to the need to copy/paste the podcast URL and upload an image,
          form completion is best undertaken on a desktop or tablet device.
        </p>
      </div>
    </div>
  </div>
  <!-- Container for adding a post form -->
  <div class="row">
    <div class="col-md-8 mt-3 offset-md-2">
      <div class="card-body">
        <!-- Form to allow users to add a blog post if logged in -->
        <form method="POST" enctype="multipart/form-data">
          <div class="form-group">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="input-group">
              <!-- Button to submit the form adding a post. Form must be approved by Site Admin before going live -->
              <button class="btn btn-style right" type="submit">Submit
              </button>
              <!-- Option to cancel if navigated to in error -->
              <input type="button" name="cancel" value="Cancel" class="anchor-btn btn-style btn-left-margin btn-cancel"
                onClick="window.location='https://fresh-casts.herokuapp.com/';return false;">
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% else %}
<!-- Information to user if navigated to in error without being signed in -->
<div class="container fluid">
  <div class="row justify-content-center">
    <div class="card-block">
      <p class="card-text">
        Sorry you must be signed in to access this page, use the button below to
        return to our homepage
      </p>
      <a href="{% url 'home' %}" role="button" class="anchor-btn btn-style">Home
      </a>
    </div>
  </div>
</div>
{% endif %} {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
  <title>Fresh Casts | {% block title %}Discover new shows!{% endblock %}</title>
  <!-- Favicon for differing browsers and devices -->
  <link rel="icon" type="image/x-icon" href="{% static 'images/fresh-casts-b-and-g-logo.ico' %}">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/fresh-casts-icon32x32.png' %}">
  <!-- Required meta tags -->
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Rick Atherton">
  <meta name="keywords"
    content="podcast blog site, podcast reviews, fresh podcasts, listen to new shows, share podcasts, comment and like podcasts">
  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:ital,wght@0,400;0,700;1,400;1,700&family=Roboto+Flex:opsz,wght@8..144,100;8..144,300;8..144,400;8..144,500;8..144,600;8..144,700&display=swap"
    rel="stylesheet">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <!-- Font Awesome Kit Tag -->
  <script src="https://kit.fontawesome.com/ac339da8f6.js" crossorigin="anonymous">
  </script>
  <!-- Fresh Casts CSS Stylesheet -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>
  <!-- Site Navigation -->
  <nav class="navbar sticky-top navbar-dark">
    <div class="container-fluid">
      <!-- Navbar left button : Toggle Main Menu (menu content line 111) -->
      <div class="nav-left-button">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapse-first"
          aria-controls="navbar-collapse-first" aria-expanded="true" aria-label="Toggle site navigation menu">
          <span class="navbar-toggler-icon">
          </span>
        </button>
      </div>
      <!-- Navbar centre section : Site Name & Logo -->
      <div class="nav-center-logo">
        <a class="navbar-brand" href="/">
          <img class="navbar-brand-image d-inline-block align-top"
            src="{% static 'images/fresh-casts-b-and-g-logo_thumbnail.webp' %}"
            alt="Fresh Casts logo">
          <h1 class="d-inline-block">Fresh Casts</h1>
        </a>
      </div>
      <!-- Navbar right button : User Features -->
      <div class="nav-right-user">
        <button class="navbar-user-icon" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapse-second"
          aria-controls="navbar-collapse-second" aria-expanded="true" aria-label="Toggle user menu">
          <i class="fa-solid fa-circle-user">
          </i>
        </button>
      </div>
      <!-- Navbar left button : Main Menu Content -->
      <div class="navbar-collapse collapse" id="navbar-collapse-first">
        <!-- Nav menu section 1 of 2 for podcast categories links -->
        <div class="nav-menu">
          <h2 class="nav-menu-header">podcast categories
          </h2>
          <ul class="nav-menu-list">
            <li class="nav-item">
              <a href="{% url 'home' %}" class="nav-link" aria-current="page">most recent
              </a>
            </li>
            <li class="nav-item">
              {% for category in categories %}
              <a href="{% url 'category' category.name %}" class="nav-link">{{category.name}}
              </a>{% endfor %}
            </li>
          </ul>
          <!-- Nav menu section 2 of 2 for additional site information links -->
          <h2 class="nav-menu-header">useful links
          </h2>
          <ul class="nav-menu-list">
            <li class="nav-item">
              <a href="{% url 'contact' %}" class="nav-link">contact us
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'about' %}" class="nav-link">about us
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'user_agreement' %}" class="nav-link">user agreement
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'accessibility_statement' %}" class="nav-link">accessibility statement
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'copyright_statement' %}" class="nav-link">copyright statement
              </a>
            </li>
          </ul>
        </div>
      </div>
      <!-- Navbar user menu aligned to nav-right-user -->
      <div class="navbar-collapse collapse" id="navbar-collapse-second">
        <ul class="navbar-nav me-auto mb-2 mt-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'add_post' %}" class="nav-link">add post
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'edit_profile' %}" class="nav-link">edit profile
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_logout' %}" class="nav-link">sign out
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a href="{% url 'sign_up' %}" class="nav-link">register
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'account_login' %}" class="nav-link">sign in
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- Container to display standard messages to the user -->
  <div class="container">
    <div class="row">
      <div class="col-md-8 offset-md-2">
        {% for message in messages %}
        <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
          {{ message | safe }}
          <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;
            </span>
          </button>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <!-- Main content where independent html templates will act as the different page views -->
  <main class="main-content">
    {% block content %}
    <!-- HTML page template content goes here -->
    {% endblock content %}
  </main>
  <!-- Footer : static throughout all pages -->
  <footer class="w-100">
    <div class="container footer-div">
      <div class="row">
        <!-- Footer column 1 of 4 for name/logo and 'Home' redirect -->
        <div class="col-sm-3">
          <h2 class="footer-header">Fresh Casts
          </h2>
          <ul class="footer-list">
            <li class="footer-item">
              <a href="{% url 'home' %}" class="footer-link">home
              </a>
            </li>
          </ul>
        </div>
        <!-- Footer column 2 of 4 for user features, dependent on login status -->
        <div class="col-sm-3">
          <h2 class="footer-header">join in
          </h2>
          <ul class="footer-list">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'add_post' %}" class="footer-link">add post
              </a>
            </li>
            <li class="footer-item">
              <a href="{% url 'edit_profile' %}" class="footer-link">edit profile
              </a>
            </li>
            <li class="footer-item">
              <a href="{% url 'account_logout' %}" class="footer-link">sign out
              </a>
            </li>
            {% else %}
            <li class="footer-item">
              <a href="{% url 'sign_up' %}" class="footer-link">register
              </a>
            </li>
            <li class="footer-item">
              <a href="{% url 'account_login' %}" class="footer-link">sign in
              </a>
            </li>
            {% endif %}
            <li class="footer-item">
              <a href="{% url 'user_agreement' %}" class="footer-link">user agreement
              </a>
            </li>
          </ul>
        </div>
        <!-- Footer column 3 of 4 for additional site information links -->
        <div class="col-sm-3">
          <h2 class="footer-header">useful links
          </h2>
          <ul class="footer-list">
            <li class="footer-item">
              <a href="{% url 'contact' %}" class="footer-link">contact us
              </a>
            </li>
            <li class="footer-item">
              <a href="{% url 'about' %}" class="footer-link">about us
              </a>
            </li>
            <li class="footer-item">
              <a href="{% url 'accessibility_statement' %}" class="footer-link">accessibility statement
              </a>
            </li>
            <li class="footer-item">
              <a href="{% url 'copyright_statement' %}" class="footer-link">copyright statement
              </a>
            </li>
          </ul>
        </div>
        <!-- Footer column 4 of 4 for social links -->
        <div class="col-sm-3">
          <h2 class="footer-header">socials
          </h2>
          <ul class="footer-list-socials">
            <li class="footer-item">
              <a href="https://facebook.com" aria-label="Go to our Facebook page" target="_blank"
                class="social-media-icon" rel="noopener noreferer"><i class="fab fa-facebook-square"></i>
              </a>
            </li>
            <li class="footer-item">
              <a href="https://instagram.com" aria-label="Go to our Instagram page" target="_blank"
                class="social-media-icon" rel="noopener noreferer"><i class="fab fa-instagram-square"></i>
              </a>
            </li>
            <li class="footer-item">
              <a href="https://youtube.com" aria-label="Go to our YouTube page" target="_blank"
                class="social-media-icon" rel="noopener noreferer"><i class="fab fa-youtube-square"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
      <!-- Footer bottom row for Copyright information -->
      <div class="row footer-copyright">
        <p class="footer-item">
          Fresh Casts © 2022.
          <br>All rights reserved
        </p>
      </div>
    </div>
  </footer>
  <!-- Bootstrap jQuery and Popper JavaScript tags -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous" defer>
  </script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous" defer>
  </script>
  <!-- Script to automatically remove user alerts after 3 seconds -->
  <script>
    document.addEventListener("DOMContentLoaded", closeAlerts);
    function closeAlerts () {
      window.setTimeout(function () {
        let messages = document.getElementById("msg");
        let alert = new bootstrap.Alert(messages);
        alert.close();
      }, 3000);
    };
  </script>
  <!-- Set independent nav menu collapsing -->
  <script>
    $('#navbar-collapse-first').on('show.bs.collapse', function () {
      $('#navbar-collapse-second').collapse('hide');
    });
    $('#navbar-collapse-second').on('show.bs.collapse', function () {
      $('#navbar-collapse-first').collapse('hide');
    });
  </script>
</body>

</html>

templates/categories.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans 'Category View' %}{% endblock %}
{% block content %}
{% if category_posts %}
<!-- Main container for page content : Post Category (displaying 1 of 5 categories) -->
<div class="container fluid">
  <!-- Page title -->
  <div class="row">
    <h2 class="card-title d-none d-lg-block" style="font-size: 2.875rem; color: #4b4a4a;">Category View</h2>
  </div>
  <br>
  <div class="row">
    <div class="card w-100 left">
      <!-- Reusing code from index.html to list all the podcasts with the same category value -->
      <div class="row">
        {% for post in category_posts %}
          {% if post.status == 1 %}
          <a href="{% url 'post_detail' post.slug %}" class="post-link">
            <div class="card-body card-hover border-bottom">
              <div class="row">
                <!-- Display either podcast post image or standard Fresh Cast logo -->
                  <div class="col-4 col-sm-2 mb-3 blog-img-div text-center">
                    {% if "placeholder" in featured_image.url %}
                    <img
                        class="img-fluid mx-auto img-min-size"
                        src="static/images/fresh-casts-b-and-g-logo_thumbnail.png"
                        alt="No podcast show logo so Fresh Casts logo used instead."
                        >
                    {% else %}
                    <img
                        class="img-fluid mx-auto img-min-size"
                        src=" {{ post.featured_image.url }}"
                        alt="Podcast show logo."
                        >
                    {% endif %}
                  </div>
                  <!-- Container for reduced post details for list view purposes -->
                  <div class="col-8 col-sm-10">
                    <div class="card-block px-2">
                      <h2 class="card-title title-link">{{ post.title }}
                      </h2>
                      <p class="card-text">{{ post.excerpt }}
                      </p>
                      <p class="author">Shared by <strong>{{ post.author }}</strong>
                      </p>
                      <p class="card-text text-left">{{ post.created_on }}
                      </p>
                      <p class="card-text">
                        <i class="far fa-heart">
                        </i>{{ post.number_of_likes }}
                      </p>
                    </div>
                  </div>
              </div>
            </div>
          </a>
          {% endif %}
        {% if forloop.counter|divisibleby:3 %}
      </div>
      {% endif %} {% endfor %}
    </div>
  </div>
  <!-- Django boilerplate ListView code to support user navigation  -->
  {% if is_paginated %}
  <nav aria-label="Page Navigation" class="page-navigation">
    <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
      <li>
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link"
           >&laquo; PREV
        </a>
      </li>
      {% endif %} {% if page_obj.has_next %}
      <li>
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">
          NEXT &raquo;
        </a
          >
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
{% else %}
<!-- Container to inform the user if a category does not exist  -->
<div class="container fluid">
  <div class="row justify-content-center">
    <div class="card-block">
      <p class="card-text">
        Sorry this category does not exist, use the button below to return to
        our homepage, or explore the categories within the main menu.
      </p>
      <a href="{% url 'home' %}" class="anchor-btn btn-style">Home
      </a>
    </div>
  </div>
</div>
{% endif %} {% endblock content %}

templates/category.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}

<div>
<form method="get">
    {{ filter.form.as_p }}
    <input type="submit" />
</form>
{% for obj in filter.qs %}
    {{ obj.category }}<br />
{% endfor %}
</div>


<!-- Container for homepage blog posts -->
<div class="container fluid">
    <div class="row">
        <div class="card w-100 left">
            <div class="row">
                {% for post in post_list %}
                <div class="card-body border-bottom">
                    <div class="row">
                        <!-- Featured image URL -->
                        <div class="col-4 col-sm-2 blog-img-div">
                            {% if "placeholder" in featured_image.url %}
                            <img class="img-fluid" src="static/images/fresh-casts-b-and-g-logo_thumbnail.png"
                                alt="Fresh Casts logo as a placeholder image for podcast image">
                            {% else %}
                            <img class="img-fluid" src=" {{ post.featured_image.url }}" alt="Image of the podcast show">
                            {% endif %}
                        </div>
                        <div class="col-8 col-sm-10">
                            <div class="card-block px-2">
                                <a href="{% url 'post_detail' post.slug %}" class="post-link">
                                    <h2 class="card-title">{{ post.title }}</h2>
                                    <p class="card-text">{{ post.excerpt }}</p>
                                    <p class="author">Shared By {{ post.author }}</p>
                                    <p class="card-text text-left">{{ post.created_on }}</p>
                                        <i class="far fa-heart"></i>{{ post.number_of_likes }}</p>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Django boilerplate ListView code to support user navigation  -->
    {% if is_paginated %}
    <nav aria-label="Page Navigation" class="page-navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>

{% endblock content %}

templates/change-password.html
{% extends "base.html" %}
{% load i18n %}
{% block head_title %}{% trans 'Change Password' %}{% endblock %}
{% block content %}
<!-- Main container for page content : Change User Password -->
<div class="container">
  <div class="row">
    <div class="col-md-8 mt-3 offset-md-2">
      <div class="card-body">
        <!-- Page title -->
        <h2 class="card-title">{% trans 'Change Password' %}
        </h2>
        <p class="card-text">
          Use this page to change your password.
          <br>
          When ready, use the button below to submit your changes.
        </p>
        <!-- List of password requirements to help user choice -->
        <ul class="card-text">
          <li>
            Your password can't be too similar to your other personal
            information.
          </li>
          <li>Your password must contain at least 8 characters.
          </li>
          <li>Your password can't be a commonly used password.
          </li>
          <li>Your password can't be entirely numeric.
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 mt-3 offset-md-2">
      <div class="card-body">
        <!-- Form for user to input Old, New1 and New2 passwords -->
        <form
              class="signup"
              method="POST"
              >
          <div class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
            {% if redirect_field_value %}
            <input
                   class="form-control"
                   type="hidden"
                   name="{{ redirect_field_name }}"
                   value="{{ redirect_field_name }}"
                   />
            {% endif %}
            <div class="input-group">
              <!-- Button to submit an update to users password -->
              <button class="btn btn-style right" type="submit">
                {% trans 'Submit' %}
              </button>
              <!-- Option to cancel if navigated to in error -->
              <input
                     type="button"
                     name="cancel"
                     value="Cancel"
                     class="anchor-btn btn-style btn-left-margin btn-cancel"
                     onClick="window.location='https://fresh-casts.herokuapp.com/';return false;"
                     />
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}